name: Flutter Android Build

on:
  push:
    branches:
      - main  # Substitua pela branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v3

      - name: Configurar Java JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Substitua pela versão específica do Flutter
          channel: 'stable'

      - name: Obter dependências
        run: flutter pub get

      - name: Build do APK Android
        run: flutter build apk --release

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk