name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ajuste de acordo com sua branch principal

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'

    - name: Install dependencies
      run: flutter pub get


    - name: Build with docker
      run: |
        mkdir build &&
        docker build -t flutter-dev . --build-arg TEST="Deu certo" --build-arg number_of_shards=5 
    - name:  Get Files
      run: |
        docker cp $(docker create flutter-dev):/app/build/web build/web
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/web'
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web

          
