name: Flutter Web Build and Deploy

on:
  push:
    branches:
      - main # ajuste de acordo com sua branch principal

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web

      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/web'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
        
    - name: Checkout
      uses: actions/checkout@v4
